### ISSUE TITLE
What's the name of your window tiling management system?

### ISSUE THREAD

**Issue by nyngwang** [solidiquis/dotfiles#3]
How you setup a clean desktop like your reddit post:

[<img src="https://user-images.githubusercontent.com/24765272/118276113-da76b080-b4f9-11eb-9378-49545f651d43.png" width="400"/>](https://user-images.githubusercontent.com/24765272/118276113-da76b080-b4f9-11eb-9378-49545f651d43.png)

---

I'm also a vim lover:

https://user-images.githubusercontent.com/24765272/118276509-51ac4480-b4fa-11eb-8ad6-ea3f6d9179c6.mov

**Comment by solidiquis** [comment]
I'm using TMUX for pane multiplexing.

**Comment by nyngwang** [comment]
In addition to alacritty/vim, I'm also wondering why all posts there have a clean desktop as shown by yours, e.g. you only have "desktop" and "code". Is this also done by an app? Or all people there are highly self-discipline :O

**Comment by solidiquis** [comment]
@nyngwang oh haha yeah I just keep my desktop clean. As you can see from the screen shot I actually do have two desktop icons on the top left corner.
